In [1]:
import pandas as pd

In [8]:
existencia_bovinas = pd.read_csv("../datos/existencias-bovinas-provincia-departamento-2008-2019.csv", encoding="latin-1")

display(existencia_bovinas)

,anio,provincia,provincia_id,departamento,departamento_id,vacas,vaquillonas,novillos,novillitos,terneros,terneras,toros,toritos,bueyes
0,2008,Buenos Aires,6,Adolfo Alsina,6007,95188.0,32850.0,34436.0,30635.0,37568.0,35323.0,4679.0,NaN,NaN
1,2009,Buenos Aires,6,Adolfo Alsina,6007,90476.0,27249.0,30725.0,30221.0,36100.0,33981.0,4153.0,NaN,NaN
2,2010,Buenos Aires,6,Adolfo Alsina,6007,73728.0,23288.0,24469.0,24146.0,26042.0,25452.0,3517.0,NaN,NaN
3,2011,Buenos Aires,6,Adolfo Alsina,6007,71648.0,30229.0,18630.0,21725.0,26302.0,25316.0,3358.0,NaN,1.0
4,2012,Buenos Aires,6,Adolfo Alsina,6007,81254.0,30784.0,19297.0,18887.0,30677.0,28833.0,3519.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5859,2015,Tucumán,90,Yerba Buena,90119,412.0,122.0,21.0,23.0,98.0,94.0,33.0,8.0,9.0
5860,2016,Tucumán,90,Yerba Buena,90119,417.0,117.0,16.0,28.0,139.0,94.0,31.0,14.0,9.0
5861,2017,Tucumán,90,Yerba Buena,90119,472.0,65.0,29.0,12.0,134.0,110.0,30.0,13.0,9.0
5862,2018,Tucumán,90,Yerba Buena,90119,437.0,58.0,32.0,13.0,54.0,22.0,28.0,9.0,9.0
5863,2019,Tucumán,90,Yerba Buena,90119,418.0,83.0,28.0,16.0,39.0,60.0,28.0,4.0,8.0

In [10]:
provincias_nea= ['Chaco', 'Corrientes', 'Misiones', 'Formosa']

existencia_bovinas_nea = existencia_bovinas[existencia_bovinas['provincia'].isin(provincias_nea)]

display(existencia_bovinas_nea)

,anio,provincia,provincia_id,departamento,departamento_id,vacas,vaquillonas,novillos,novillitos,terneros,terneras,toros,toritos,bueyes
1649,2008,Chaco,22,2 de Abril,22039,12264.0,5053.0,2364.0,2269.0,2274.0,2699.0,781.0,NaN,NaN
1650,2009,Chaco,22,2 de Abril,22039,11412.0,5137.0,1877.0,2185.0,2360.0,2621.0,717.0,NaN,NaN
1651,2010,Chaco,22,2 de Abril,22039,10269.0,4021.0,1030.0,1968.0,2349.0,2225.0,686.0,NaN,NaN
1652,2011,Chaco,22,2 de Abril,22039,10731.0,4092.0,1383.0,1837.0,2565.0,2941.0,745.0,NaN,NaN
1653,2012,Chaco,22,2 de Abril,22039,11950.0,4331.0,1359.0,1876.0,3034.0,3117.0,740.0,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4073,2015,Misiones,54,25 de Mayo,54119,14310.0,4992.0,2057.0,1272.0,3312.0,4512.0,1103.0,NaN,1223.0
4074,2016,Misiones,54,25 de Mayo,54119,14775.0,4729.0,1314.0,1684.0,3502.0,4698.0,1118.0,3.0,1034.0
4075,2017,Misiones,54,25 de Mayo,54119,15368.0,5297.0,891.0,2021.0,3650.0,4716.0,1189.0,933.0,89.0
4076,2018,Misiones,54,25 de Mayo,54119,14717.0,4487.0,290.0,2069.0,3201.0,4176.0,1028.0,125.0,870.0
4077,2019,Misiones,54,25 de Mayo,54119,14379.0,4325.0,243.0,2130.0,3251.0,4092.0,973.0,172.0,834.0

In [14]:
#movimientos_2016 = pd.read_csv("../datos/movimiento-bovinos-2016.csv", encoding="latin-1")

#movimientos_2017 = pd.read_csv("../datos/movimiento-bovinos-2017.csv", encoding="latin-1")

movimientos_2018 = pd.read_csv("../datos/movimiento-bovinos-2018.csv", encoding="latin-1")

#movimientos_2016_nea = movimientos_2016[movimientos_2016['provincia_origen'].isin(provincias_nea) | movimientos_2016['provincia_destino'].isin(provincias_nea)]

#movimientos_2017_nea = movimientos_2017[movimientos_2016['provincia_origen'].isin(provincias_nea) | movimientos_2017['provincia_destino'].isin(provincias_nea)]

movimientos_2018_nea = movimientos_2018[movimientos_2018['provincia_origen'].isin(provincias_nea) | movimientos_2018['provincia_destino'].isin(provincias_nea)]

In [15]:
display(movimientos_2018_nea)

,fecha,salido_de,ingresado_a,provincia_origen,provincia_origen_id,departamento_origen,departamento_origen_id,provincia_destino,provincia_destino_id,departamento_destino,departamento_destino_id,vaca,vaquillona,novillo,novillito,ternero,ternera,torito,toro,bueyes
817,2018-01,Establecimiento,Establecimiento,Buenos Aires,6,General La Madrid,6322,Corrientes,18,Paso de los Libres,18119,0,0,0,0,0,0,40,0,0
1598,2018-01,Establecimiento,Establecimiento,Buenos Aires,6,Saladillo,6707,Formosa,34,Patiño,34035,0,34,0,0,0,0,0,1,0
1887,2018-01,Establecimiento,Establecimiento,Chaco,22,1° de Mayo,22126,Chaco,22,1° de Mayo,22126,100,31,24,37,88,92,6,9,0
1888,2018-01,Establecimiento,Establecimiento,Chaco,22,1° de Mayo,22126,Chaco,22,25 de Mayo,22168,0,0,0,0,45,25,0,0,0
1889,2018-01,Establecimiento,Establecimiento,Chaco,22,1° de Mayo,22126,Chaco,22,Bermejo,22014,15,2,0,3,14,7,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168527,2018-12,Remate feria,Frigorífico,Corrientes,18,Ituzaingó,18084,Santa Fe,82,General Obligado,82049,19,0,5,0,0,0,0,7,0
168528,2018-12,Remate feria,Frigorífico,Corrientes,18,Mercedes,18105,Buenos Aires,6,General Las Heras,6329,71,1,5,0,0,0,0,6,0
168529,2018-12,Remate feria,Frigorífico,Corrientes,18,Mercedes,18105,Corrientes,18,Mercedes,18105,5,4,0,0,0,0,0,0,0
168654,2018-12,Remate feria,Frigorífico,Santa Fe,82,Castellanos,82021,Corrientes,18,Paso de los Libres,18119,31,0,0,0,0,0,0,0,0
168755,2018-12,Remate feria,Frigorífico,Santa Fe,82,San Jerónimo,82105,Misiones,54,Candelaria,54021,25,29,0,0,0,0,0,0,0

In [16]:
movimientos_2018_nea.to_csv("../datos/movimiento-bovino-2018-nea.csv", index=False)